// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOCKY4ISBb9z6DZrypx3j6UakD9gKStNE',
    appId: '1:361933932223:web:ee181133ecb7777f27280a',
    messagingSenderId: '361933932223',
    projectId: 'sherophopia-11097',
    authDomain: 'sherophopia-11097.firebaseapp.com',
    storageBucket: 'sherophopia-11097.appspot.com',
    measurementId: 'G-BPPSVH06R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtexqc2Oxpx2eZLGX2rEe23dim4EG0094',
    appId: '1:361933932223:android:8a6f05bcfe3aa7ff27280a',
    messagingSenderId: '361933932223',
    projectId: 'sherophopia-11097',
    storageBucket: 'sherophopia-11097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfrEChYxPfbhuw-atT3p4c9VUD6Foz-WA',
    appId: '1:361933932223:ios:7494e7d21a08d0db27280a',
    messagingSenderId: '361933932223',
    projectId: 'sherophopia-11097',
    storageBucket: 'sherophopia-11097.appspot.com',
    iosBundleId: 'com.example.sherophopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfrEChYxPfbhuw-atT3p4c9VUD6Foz-WA',
    appId: '1:361933932223:ios:7494e7d21a08d0db27280a',
    messagingSenderId: '361933932223',
    projectId: 'sherophopia-11097',
    storageBucket: 'sherophopia-11097.appspot.com',
    iosBundleId: 'com.example.sherophopia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOCKY4ISBb9z6DZrypx3j6UakD9gKStNE',
    appId: '1:361933932223:web:2da54e9ec0f76a1b27280a',
    messagingSenderId: '361933932223',
    projectId: 'sherophopia-11097',
    authDomain: 'sherophopia-11097.firebaseapp.com',
    storageBucket: 'sherophopia-11097.appspot.com',
    measurementId: 'G-YPXTB0JW81',
  );

}